name: ci-cd

on: [push, pull_request]

jobs:
  ci:
    # Set up operating system
    runs-on: ubuntu-latest

    # Define job steps
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python 3.9
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install poetry
      uses: snok/install-poetry@v1

    - name: Install package
      run: poetry install

    - name: Run tests with pytest
      run: poetry run pytest tests/
